dist: trusty
language: java
sudo: true
before_install:
- sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
- sudo apt-get update
jdk:
- oraclejdk8
script:
- sudo apt-get install doxygen; sudo apt-get
  install texlive-fonts-recommended; sudo apt-get install texlive-generic-recommended;
  sudo apt-get install texlive-latex-extra; sudo apt-get install texlive-latex-recommended;
  sudo apt-get install texlive-extra-utils; sudo apt-get install texlive-font-utils;
  sudo apt-get install ghostscript; sudo apt-get install graphviz; sudo apt-get install
  latex-xcolor; sudo apt-get install rdfind; else echo 'Not on master-will not install
  tex'; fi
- mvn test -B
after_success:
- doxygen Doxygen
- sudo chmod +x build_tex.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Ztna0CgVo4UermagK3jjjEburFVZZDDmT4Bq8Q549fzb1oreZ0ARFKtlre4nFJ/b5CQZH/ToxAR7u5L55N7dyBB4vnWhkzDcmskrMg+5fDbONlT8ygMx0NcC20whQeR2f6U3lUh2GSC1DXkw3mRMv3X7ikfjg+Krs+qz16/YQkPeM3TuM2u0tIf73glBXaPipyhctPqysi8gK4Z6AoMmVbNaGvfnnqgmCLwswBhyKMNqlUPo3XYIcqfB832Qjxq1RsiY15Lw3SC6ZNoccoydyErx1hnENhEPlzGcwoiGX7nVAWYjOhSTivYNeVOOCQo3bO10K6GrrPO9+jNhcGt7ZuZcV9krDP3MQnYCphLgrPtCXlZSEcOwlhNPN4UCxwBd5RUYS24xHu7rFZBo7X4/WlGThCcypIuobTN0wqkBsIMKtPIt7S3IRmoqkuG159F2rW0zDIIdNIMJAqS40GUJR72WUwymQVE9bNIss4fBVWU+XuHe8UIA/x87t/WSMl0HckK9B+Z6UuqTzt12GfZHNQhxrpwPo9YY2o5NFWpqAdgK3xFUUlykC65vHgkRd52z44F2TlojDtZWWFO1ZjSN7a1XT1NpuXXm4MyiCvw6xBwtpJajD2OCJuBLhqhTIJhtGAFp3HL3VfpMUhoG9PJLbiTmHQtbpLXhAioen8c05cU=
  file: docs/
  on:
    repo: michaelghaben/ece1186
