dist: trusty
language: java
sudo: true
before_install:
#- sudo add-apt-repository ppa:jonathonf/texlive-2016 -y
- sudo apt-get update
- gem install dpl
jdk:
- oraclejdk8
script:
- sudo apt-get install doxygen;sudo apt-get install graphviz; sudo apt-get install rdfind;
- mvn test -B
