package TrainControllerComps;

import TrainModel.Train;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * This class is responsible for displaying information regarding the block the selected train is 
 * currently in. This class collaborates with the Train class as well as the 
 * Train Controller class. 
 * 
 * @author Andrew Lendacky
 */
public class TCBlockInfoPanel extends javax.swing.JPanel {

    
    /**
     * The train to use in order to populate the labels and UI elements. 
     * This property must be passed in from the Train Controller class. 
     */
    private Train selectedTrain; 
 
    /**
     * Used to keep track if the system is in Manual or Automatic mode. 
     * This is passed is from the Train Controller class. 
     */
    private boolean inManualMode; 
  
    /**
     * Constructor for a TCBlockInfoPanel object. This constructor does not set 
     * the selected train, and must be set by the Train Controller before being used. 
     */
    public TCBlockInfoPanel() {
        initComponents();
    }
    
    /**
     * Sets the selected train that the class will get its information from. 
     * This train is set from the Train Controller class. 
     * 
     * @param train the selected train
     */
    public void setSelectedTrain(Train train){
        
        this.selectedTrain = train; 
    }
    
    /**
     * Sets the block speed label to a specified speed in MPH. 
     * 
     * @param blockSpeed the speed of the block the train is in. 
     */
    public void setBlockSpeed(double blockSpeed){
        
        this.blockSpeed.setText(Double.toString(blockSpeed));
    }
    
    /**
     * Gets the speed of the block the selected train is in. 
     * 
     * @return returns the block speed
     */
    public double getBlockSpeed(){
        
        return Double.parseDouble(this.blockSpeed.getText());
    }
    
    /**
     * Refreshes the UI elements on the GUI to display information corresponding to the 
     * selected train. 
     * 
     */
    public void refreshUI(){
           
//        if (this.selectedTrain.getGPS()!= null){
//        
//            if (this.selectedTrain.getGPS().getCurrBlock() != null){
//            
//                this.blockSpeed.setText(Double.toString( this.selectedTrain.getGPS().getCurrBlock().getSpeedLimit() ));
//                this.currentBlock.setText(Integer.toString( this.selectedTrain.getGPS().getCurrBlock().blockNum() )); 
//            }
//        }
    }
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentBlockLabel = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        unitLabel = new javax.swing.JLabel();
        blockSpeed = new javax.swing.JLabel();
        blockSpeedLabel1 = new javax.swing.JLabel();
        currentBlock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        currentBlockLabel.setBackground(new java.awt.Color(255, 255, 255));
        currentBlockLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentBlockLabel.setText("Current Block:");

        unitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        unitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unitLabel.setText("MPH");

        blockSpeed.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        blockSpeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blockSpeed.setText("0");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(unitLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(blockSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitLabel)
                .addContainerGap())
        );

        blockSpeedLabel1.setBackground(new java.awt.Color(255, 255, 255));
        blockSpeedLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        blockSpeedLabel1.setText("Block Speed:");

        currentBlock.setBackground(new java.awt.Color(255, 255, 255));
        currentBlock.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentBlock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentBlock.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blockSpeedLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentBlockLabel)
                                .addGap(18, 18, 18)
                                .addComponent(currentBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentBlockLabel)
                    .addComponent(currentBlock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockSpeedLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel blockSpeed;
    private javax.swing.JLabel blockSpeedLabel1;
    private javax.swing.JLabel currentBlock;
    private javax.swing.JLabel currentBlockLabel;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
