package TrainControllerComps;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * This class is responsible for displaying information regarding the block the selected train is 
 * currently in. This class collaborates with the Train class as well as the 
 * Train Controller class. 
 * 
 * @author Andrew Lendacky
 */
public class TCBlockInfoPanel extends javax.swing.JPanel {

    
    /**
     * The train to use in order to populate the labels and UI elements. 
     * This property must be passed in from the Train Controller class. 
     * 
     */
    private TestTrain selectedTrain; 
    
    /**
     * Constructor for a TCBlockInfoPanel object. This constructor does not set 
     * the selected train, and must be set by the Train Controller before being used. 
     * 
     */
    public TCBlockInfoPanel() {
        initComponents();
    }
    
    /**
     * Sets the selected train that the class will get its information from. 
     * This train is set from the Train Controller class. 
     * 
     * @param train the selected train
     */
    public void setSelectedTrain(TestTrain train){
        
        this.selectedTrain = train; 
    }
    
    /**
     * Sets the block speed label to a specified speed in MPH. 
     * 
     * @param blockSpeed the speed of the block the train is in. 
     */
    public void setBlockSpeed(double blockSpeed){
        
        this.blockSpeed.setText(Double.toString(blockSpeed));
    }
    
    /**
     * Gets the speed of the block the selected train is in. 
     * 
     * @return returns the block speed
     */
    public double getBlockSpeed(){
        
        return Double.parseDouble(this.blockSpeed.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blockSpeedLabel = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        unitLabel = new javax.swing.JLabel();
        blockSpeed = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        blockSpeedLabel.setBackground(new java.awt.Color(255, 255, 255));
        blockSpeedLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        blockSpeedLabel.setText("Block Speed:");

        unitLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        unitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unitLabel.setText("MPH");

        blockSpeed.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        blockSpeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blockSpeed.setText("0");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(unitLabel)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blockSpeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unitLabel)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blockSpeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel blockSpeed;
    private javax.swing.JLabel blockSpeedLabel;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
