package TrainControllerComps;

import java.awt.List;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
public class TCDispatchedTrainFrame extends javax.swing.JFrame {

    private HashMap<String, TestTrain> dispatchedTrains;
    
    LinkedList<String> selectedTrains; 
    /**
     * Creates new form TCDispatchedTrainFrame
     */
    public TCDispatchedTrainFrame() {
        initComponents();
        
    }
    
    public TCDispatchedTrainFrame(HashMap<String, TestTrain> dispatchedTrains) {
        initComponents();
        
        this.dispatchedTrains = dispatchedTrains;
        this.selectedTrains = new LinkedList<String>(); 
        this.refreshUI();
    }
    
    private void refreshUI(){
    
        String[] keys = new String[this.dispatchedTrains.keySet().size()];
        int counter = 0; 
        for (String key : this.dispatchedTrains.keySet()){
        
            keys[counter] = key; 
            counter++; 
        }
        
        this.dispatchedTrains_List.setListData(keys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dispatchedTrains_List = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        selectAll_Btn = new javax.swing.JButton();
        deselectAll_Btn = new javax.swing.JButton();
        openSelected_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dispatchedTrains_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Train 1", "Train 2", "Train 3", "Train 4", "Train 5", "Train 6", "Train 7", "Train 8", "Train 9", "Train 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        dispatchedTrains_List.setToolTipText("List of dispatched trains.");
        jScrollPane2.setViewportView(dispatchedTrains_List);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Dispatched Trains");

        selectAll_Btn.setText("Select All");
        selectAll_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAll_BtnActionPerformed(evt);
            }
        });

        deselectAll_Btn.setText("Deselect All");
        deselectAll_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAll_BtnActionPerformed(evt);
            }
        });

        openSelected_Btn.setText("Open Selected");
        openSelected_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSelectedTrains(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectAll_Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deselectAll_Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openSelected_Btn)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAll_Btn)
                    .addComponent(deselectAll_Btn)
                    .addComponent(openSelected_Btn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectAll_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAll_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectAll_BtnActionPerformed

    private void deselectAll_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectAll_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deselectAll_BtnActionPerformed

    private void openSelectedTrains(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSelectedTrains
        // TODO add your handling code here:
        
        TestTrain train; 
        //this.selectedTrains = (LinkedList<String>) this.dispatchedTrains_List.getSelectedValuesList();
        for (String trainId : this.dispatchedTrains_List.getSelectedValuesList()){
        
            train = this.dispatchedTrains.get(trainId);
            TrainController newTC = new TrainController(train);
            newTC.setVisible(true);
            newTC.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
       
    }//GEN-LAST:event_openSelectedTrains

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCDispatchedTrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCDispatchedTrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCDispatchedTrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCDispatchedTrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCDispatchedTrainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deselectAll_Btn;
    private javax.swing.JList<String> dispatchedTrains_List;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton openSelected_Btn;
    private javax.swing.JButton selectAll_Btn;
    // End of variables declaration//GEN-END:variables
}
