package TrainControllerComps;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
public class TCEngineerPanel extends javax.swing.JFrame {

    private TestTrain selectedTrain; 
    
    /**
     * Creates new form TCEngineerPanel
     */
    public TCEngineerPanel() {
        initComponents();
    }
    
    /**
     * Constructor that creates an Engineer Panel with a give train. 
     * 
     * @param train the train whose Kp and Ki you want to change
     */
    public TCEngineerPanel(TestTrain train){
            
        this.initComponents();
        
        this.selectedTrain = train;
        this.refreshUI();
    }
    
    private void refreshUI(){
    
        this.trainId.setText(this.selectedTrain.id); 
        
        if (this.selectedTrain.kp != null && this.selectedTrain.ki != null){
        
            this.Kp_TextField.setText(Double.toString(this.selectedTrain.kp));
            this.Ki_TextField.setText(Double.toString(this.selectedTrain.ki));
        }else{
        
            this.Kp_TextField.setText("0.0");
            this.Ki_TextField.setText("0.0");
        }
    }
    
    public void setTrain(TestTrain train){
        
        this.selectedTrain = train;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ki_TextField = new javax.swing.JTextField();
        Kp_TextField = new javax.swing.JTextField();
        setConstants = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        trainId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Kp: ");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Ki: ");

        Ki_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Ki_TextField.setText("0.0");

        Kp_TextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Kp_TextField.setText("0.0");
        Kp_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kp_TextFieldActionPerformed(evt);
            }
        });

        setConstants.setText("Set");
        setConstants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setConstants(evt);
            }
        });

        jLabel2.setText(" Train ID:");

        trainId.setText("(id_here)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(setConstants, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ki_TextField)
                            .addComponent(Kp_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(trainId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(trainId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Kp_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ki_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setConstants)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setConstants(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setConstants
               
        if (this.selectedTrain != null){
            
            System.out.println("Kp_TextField: " + this.Kp_TextField.getText());             
            System.out.println("Ki_TextField: " + this.Ki_TextField.getText());
            
            // give the train the set Kp and Ki
            this.selectedTrain.kp = Double.parseDouble(this.Kp_TextField.getText());
            this.selectedTrain.ki = Double.parseDouble(this.Ki_TextField.getText());
            
            System.out.println("Kp: " + this.selectedTrain.kp);             
            System.out.println("Ki: " + this.selectedTrain.ki); 
            
            this.dispose();
            
        }else{
            System.out.println("No Train Selected"); 
        }
        
        
        
    }//GEN-LAST:event_setConstants

    private void Kp_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kp_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kp_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCEngineerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCEngineerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCEngineerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCEngineerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCEngineerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ki_TextField;
    private javax.swing.JTextField Kp_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton setConstants;
    private javax.swing.JLabel trainId;
    // End of variables declaration//GEN-END:variables
}
