package TrainControllerComps;

import CTC.TrainManager;
import TrackModel.Block;
import TrainModel.Train;
import WaysideController.PLC;
import WaysideController.WS;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.LinkedList;
import java.util.Random;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * This class is responsible for testing the various components in the Train Controller, mimicking the components on 
 * a train object. 
 * 
 * This class collaborates with the Train Controller and Train class. 
 * 
 * @author Andrew Lendacky
 */
public class TCTestConsole extends javax.swing.JFrame {

    /**
     * Train being controlled by the Train Controller.
     */
    private Train selectedTrain; 
    
    /**
     * Train Controller to relay any changes made to the train to.
     */
    private TrainController trainController; 
        
  
    /**
     * The number of dispatched trains in the system
     */
    private int dispatchedTrains; 
    
    
    WS ws; 
    TrainManager tm; 
    Block yardBlock; 
    Block endingBlock; 
            
    /**
     * Constructor for creating a TCTestConsole object with no Train Controller and no 
     * selected train. 
     */
    public TCTestConsole(TrainController trainCont) {
        initComponents();
        
        this.dispatchedTrains = 0; 
        this.selectedTrain = null; 
        this.trainController = trainCont; 
             
        this.setupTestScenario();  
    }
        
    /**
     * Creates new form TCTestConsole
     */
    public TCTestConsole(Train train, TrainController trainCont) {
        initComponents();
        
        this.dispatchedTrains = 0; 
        this.selectedTrain = train; 
        this.trainController = trainCont; 
       
        this.setupTestScenario();
    }
    
    
    private void setupTestScenario(){
        
        // create dummy data
        ws = new WS("Red", this.trainController.track);
        tm = new TrainManager("Red", this.trainController.track);
        
        yardBlock = this.trainController.track.getBlock("Red", "U", new Integer(77));
        yardBlock.setSuggestedSpeed(35.0);
        
        this.trainController.track.getBlock("Red", "C", new Integer(9)).setSwitchState(0);
        endingBlock = this.trainController.track.getBlock("Red", "B", new Integer(6));          
    }
         
    /**
     * 
     * 
     * @param trainCont 
     */
    private void setTrainController(TrainController trainCont){
    
        this.trainController = trainCont;
    }
    
    /**
     * 
     * 
     * @param train 
     */
    public void setTrain(Train train){
    
        this.selectedTrain = train; 
    }
    
    /**
     * 
     * 
     * 
     */
    public void refreshUI(){
    
       if (this.selectedTrain != null){
            // update labels
            this.trainSpeed.setText(Double.toString(this.selectedTrain.getVelocity()));
            
            double powerKW = this.selectedTrain.getPower()/1000; 
            this.trainPower.setText(Double.toString(powerKW));
            this.setSpeed.setText(Double.toString(this.trainController.getSpeedController().getSetSpeed())); 
            // 
       } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acButtonGroupMurphy = new javax.swing.ButtonGroup();
        heatButtonGroupMurphy = new javax.swing.ButtonGroup();
        lightsButtonGroupMurphy = new javax.swing.ButtonGroup();
        leftDoorsButtonGroupMurphy = new javax.swing.ButtonGroup();
        rightDoorsButtonGroupMurphy = new javax.swing.ButtonGroup();
        acButtonGroup = new javax.swing.ButtonGroup();
        heatButtonGroup = new javax.swing.ButtonGroup();
        lightsButtonGroup = new javax.swing.ButtonGroup();
        leftDoorsButtonGroup = new javax.swing.ButtonGroup();
        rightDoorsButtonGroups = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        trainSpeedLabel = new javax.swing.JLabel();
        trainPowerLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        breakACMurphy = new javax.swing.JRadioButton();
        fixACMurphy = new javax.swing.JRadioButton();
        breakHeatMurphy = new javax.swing.JRadioButton();
        fixHeatMurphy = new javax.swing.JRadioButton();
        breakLightsMurphy = new javax.swing.JRadioButton();
        fixLightsMurphy = new javax.swing.JRadioButton();
        breakLeftDoorsMurphy = new javax.swing.JRadioButton();
        fixLeftDoorsMurphy = new javax.swing.JRadioButton();
        breakRightDoorsMurphy = new javax.swing.JRadioButton();
        fixRightDoorsMurphy = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        acLabel = new javax.swing.JLabel();
        heatLabel = new javax.swing.JLabel();
        lightsLabel = new javax.swing.JLabel();
        rightDoorsLabel = new javax.swing.JLabel();
        leftDoorsLabel = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        trainSpeed = new javax.swing.JLabel();
        trainPower = new javax.swing.JLabel();
        setSpeed = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        dispatchTrainsButton = new javax.swing.JButton();
        numDispatchedTrains = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        trainSpeedLabel.setText("Speed:");

        trainPowerLabel.setText("Power:");

        jLabel5.setText("Set Speed: ");

        jLabel6.setText("Authority (Block Id):");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText(" MPH");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("kW");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("MPH");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Murphy");

        jLabel12.setText("AC:");

        jLabel13.setText("Heat:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Lights:");

        jLabel15.setText("Left Door:");

        jLabel16.setText("Right Door:");

        acButtonGroupMurphy.add(breakACMurphy);
        breakACMurphy.setText("Break");
        breakACMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakAC(evt);
            }
        });

        acButtonGroupMurphy.add(fixACMurphy);
        fixACMurphy.setText("Unbreak");
        fixACMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixAC(evt);
            }
        });

        heatButtonGroupMurphy.add(breakHeatMurphy);
        breakHeatMurphy.setText("Break");
        breakHeatMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakHeat(evt);
            }
        });

        heatButtonGroupMurphy.add(fixHeatMurphy);
        fixHeatMurphy.setText("Unbreak");
        fixHeatMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixHeat(evt);
            }
        });

        lightsButtonGroupMurphy.add(breakLightsMurphy);
        breakLightsMurphy.setText("Break");
        breakLightsMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakLightsMurphy(evt);
            }
        });

        lightsButtonGroupMurphy.add(fixLightsMurphy);
        fixLightsMurphy.setText("Unbreak");
        fixLightsMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixLights(evt);
            }
        });

        leftDoorsButtonGroupMurphy.add(breakLeftDoorsMurphy);
        breakLeftDoorsMurphy.setText("Break");
        breakLeftDoorsMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakLeftDoors(evt);
            }
        });

        leftDoorsButtonGroupMurphy.add(fixLeftDoorsMurphy);
        fixLeftDoorsMurphy.setText("Unbreak");
        fixLeftDoorsMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixLeftDoors(evt);
            }
        });

        rightDoorsButtonGroupMurphy.add(breakRightDoorsMurphy);
        breakRightDoorsMurphy.setText("Break");
        breakRightDoorsMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakRightDoors(evt);
            }
        });

        rightDoorsButtonGroupMurphy.add(fixRightDoorsMurphy);
        fixRightDoorsMurphy.setText("Unbreak");
        fixRightDoorsMurphy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixRightDoors(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        acLabel.setText("AC:");

        heatLabel.setText("Heat:");

        lightsLabel.setText("Lights:");

        rightDoorsLabel.setText("Right Door:");

        leftDoorsLabel.setText("Left Door:");

        acButtonGroup.add(jRadioButton11);
        jRadioButton11.setText("ON");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOnAC(evt);
            }
        });

        acButtonGroup.add(jRadioButton12);
        jRadioButton12.setText("OFF");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffAC(evt);
            }
        });

        heatButtonGroup.add(jRadioButton13);
        jRadioButton13.setText("OFF");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffHeat(evt);
            }
        });

        heatButtonGroup.add(jRadioButton14);
        jRadioButton14.setText("ON");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOnHeat(evt);
            }
        });

        lightsButtonGroup.add(jRadioButton15);
        jRadioButton15.setText("ON");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOnLights(evt);
            }
        });

        lightsButtonGroup.add(jRadioButton16);
        jRadioButton16.setText("OFF");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffLights(evt);
            }
        });

        leftDoorsButtonGroup.add(jRadioButton17);
        jRadioButton17.setText("OPEN");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openLeftDoors(evt);
            }
        });

        leftDoorsButtonGroup.add(jRadioButton18);
        jRadioButton18.setText("CLOSE");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeLeftDoors(evt);
            }
        });

        rightDoorsButtonGroups.add(jRadioButton19);
        jRadioButton19.setText("OPEN");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRightDoors(evt);
            }
        });

        rightDoorsButtonGroups.add(jRadioButton20);
        jRadioButton20.setText("CLOSE");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRightDoors(evt);
            }
        });

        trainSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        trainSpeed.setText("0");

        trainPower.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        trainPower.setText("0");

        setSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setSpeed.setText("0");

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("0");

        dispatchTrainsButton.setText("Dispatch 'x' Trains");
        dispatchTrainsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispatchTrains(evt);
            }
        });

        numDispatchedTrains.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trainSpeedLabel)
                            .addComponent(trainPowerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(trainPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(trainSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(36, 36, 36)
                                .addComponent(setSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(15, 15, 15)
                                        .addComponent(breakLeftDoorsMurphy))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(breakRightDoorsMurphy))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(breakHeatMurphy)
                                            .addComponent(breakACMurphy)
                                            .addComponent(breakLightsMurphy))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fixLeftDoorsMurphy)
                                    .addComponent(fixRightDoorsMurphy)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fixHeatMurphy)
                                        .addComponent(fixACMurphy)
                                        .addComponent(fixLightsMurphy))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dispatchTrainsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numDispatchedTrains, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(acLabel)
                            .addComponent(heatLabel)
                            .addComponent(lightsLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leftDoorsLabel)
                                    .addComponent(rightDoorsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton17)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jRadioButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton15)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton16)
                                            .addComponent(jRadioButton18)
                                            .addComponent(jRadioButton13)
                                            .addComponent(jRadioButton12))))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(trainSpeedLabel)
                                .addComponent(trainSpeed)))
                        .addGap(18, 18, 18)
                        .addComponent(trainPowerLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(setSpeed))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel34)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(trainPower))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(dispatchTrainsButton)
                            .addComponent(numDispatchedTrains, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(breakACMurphy))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(breakHeatMurphy))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(breakLightsMurphy))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(breakLeftDoorsMurphy)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fixACMurphy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fixHeatMurphy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fixLightsMurphy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fixLeftDoorsMurphy)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(breakRightDoorsMurphy))
                                    .addComponent(fixRightDoorsMurphy)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(acLabel)
                                            .addComponent(jRadioButton12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButton13)
                                            .addComponent(heatLabel)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton15)
                                    .addComponent(lightsLabel)
                                    .addComponent(jRadioButton16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton17)
                                    .addComponent(jRadioButton18)
                                    .addComponent(leftDoorsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton19)
                                        .addComponent(jRadioButton20))
                                    .addComponent(rightDoorsLabel)))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void breakAC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakAC
        this.selectedTrain.setAC( -1 );    
    }//GEN-LAST:event_breakAC

    private void fixAC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixAC
        
        this.selectedTrain.setAC( 0 ); 
    }//GEN-LAST:event_fixAC

    private void breakHeat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakHeat
        
        this.selectedTrain.setHeat( -1 );
    }//GEN-LAST:event_breakHeat

    private void fixHeat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixHeat
        
        this.selectedTrain.setHeat( 0 ); 
    }//GEN-LAST:event_fixHeat

    private void breakLightsMurphy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakLightsMurphy
        this.selectedTrain.setLights( -1 );
    }//GEN-LAST:event_breakLightsMurphy

    private void fixLights(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixLights
        this.selectedTrain.setLights( 0 ); 
    }//GEN-LAST:event_fixLights

    private void breakLeftDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakLeftDoors
        
        this.selectedTrain.setLeftDoor( -1 );
    }//GEN-LAST:event_breakLeftDoors

    private void fixLeftDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixLeftDoors
        
        this.selectedTrain.setLeftDoor( 0 );
    }//GEN-LAST:event_fixLeftDoors

    private void breakRightDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakRightDoors
        this.selectedTrain.setRightDoor( -1 );
    }//GEN-LAST:event_breakRightDoors

    private void fixRightDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixRightDoors
        this.selectedTrain.setRightDoor( 0 ); 
    }//GEN-LAST:event_fixRightDoors

    private void turnOnAC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOnAC
        
        this.selectedTrain.setAC( 1 );
    }//GEN-LAST:event_turnOnAC

    private void turnOffAC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffAC
        
        this.selectedTrain.setAC( 0 );
    }//GEN-LAST:event_turnOffAC

    private void turnOnHeat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOnHeat
        
        this.selectedTrain.setHeat( 1 );
    }//GEN-LAST:event_turnOnHeat

    private void turnOffHeat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffHeat
       
        this.selectedTrain.setHeat( 0 );
    }//GEN-LAST:event_turnOffHeat

    private void turnOnLights(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOnLights
        
        this.selectedTrain.setLights( 1 );
    }//GEN-LAST:event_turnOnLights

    private void turnOffLights(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffLights
        
        this.selectedTrain.setLights( 0 );
    }//GEN-LAST:event_turnOffLights

    private void openLeftDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openLeftDoors
        
        this.selectedTrain.setLeftDoor( 1 );
    }//GEN-LAST:event_openLeftDoors

    private void closeLeftDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeLeftDoors
        
        this.selectedTrain.setLeftDoor( 0 );
    }//GEN-LAST:event_closeLeftDoors

    private void openRightDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRightDoors
        
        this.selectedTrain.setRightDoor(1);
    }//GEN-LAST:event_openRightDoors

    private void closeRightDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRightDoors
        
        this.selectedTrain.setRightDoor( 0 );
    }//GEN-LAST:event_closeRightDoors

    private void dispatchTrains(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispatchTrains
       
        // get value from combo box
   
        String value = (String) this.numDispatchedTrains.getSelectedItem();
        
        // add to the list of dispatched trains 
        System.out.println("Dispatching " + value + " trains."); 
               
        for (int i = 0; i < Integer.parseInt(value); i++){
            
            // FIX ME: Get this integrated with the Track model.
            //this.trainController.trains.add(new Train( i, this.trainController.track) );
            this.dispatchedTrains++;             
            this.trainController.trainHandler.setSpeedAndAuthority(-1, 35.0, this.endingBlock, this.yardBlock);
           
            this.selectedTrain = this.trainController.trainHandler.findTrain(this.dispatchedTrains);
        }
        
        this.trainController.setTrainListComboBox();
    }//GEN-LAST:event_dispatchTrains

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCTestConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCTestConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCTestConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCTestConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TCTestConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup acButtonGroup;
    private javax.swing.ButtonGroup acButtonGroupMurphy;
    private javax.swing.JLabel acLabel;
    private javax.swing.JRadioButton breakACMurphy;
    private javax.swing.JRadioButton breakHeatMurphy;
    private javax.swing.JRadioButton breakLeftDoorsMurphy;
    private javax.swing.JRadioButton breakLightsMurphy;
    private javax.swing.JRadioButton breakRightDoorsMurphy;
    private javax.swing.JButton dispatchTrainsButton;
    private javax.swing.JRadioButton fixACMurphy;
    private javax.swing.JRadioButton fixHeatMurphy;
    private javax.swing.JRadioButton fixLeftDoorsMurphy;
    private javax.swing.JRadioButton fixLightsMurphy;
    private javax.swing.JRadioButton fixRightDoorsMurphy;
    private javax.swing.ButtonGroup heatButtonGroup;
    private javax.swing.ButtonGroup heatButtonGroupMurphy;
    private javax.swing.JLabel heatLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.ButtonGroup leftDoorsButtonGroup;
    private javax.swing.ButtonGroup leftDoorsButtonGroupMurphy;
    private javax.swing.JLabel leftDoorsLabel;
    private javax.swing.ButtonGroup lightsButtonGroup;
    private javax.swing.ButtonGroup lightsButtonGroupMurphy;
    private javax.swing.JLabel lightsLabel;
    private javax.swing.JComboBox<String> numDispatchedTrains;
    private javax.swing.ButtonGroup rightDoorsButtonGroupMurphy;
    private javax.swing.ButtonGroup rightDoorsButtonGroups;
    private javax.swing.JLabel rightDoorsLabel;
    private javax.swing.JLabel setSpeed;
    private javax.swing.JLabel trainPower;
    private javax.swing.JLabel trainPowerLabel;
    private javax.swing.JLabel trainSpeed;
    private javax.swing.JLabel trainSpeedLabel;
    // End of variables declaration//GEN-END:variables
}
