package TrainControllerComps;

import TrainModel.*;
import java.math.RoundingMode;
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * A component of the Train Controller responsible for the selected train's speed, power, authority, and suggested speed. 
 *
 * This class collaborates with the Train Controller and Train class. 
 * 
 * @author Andrew Lendacky
 */
public class TCTrainInfoPane extends javax.swing.JPanel {

    /**
     * The train used to update the UI based on its information.
     */
    private Train selectedTrain; 
    
    /**
     * Constructor for creating a TCTrainInfoPane object with no selected train.
     * The selected train must be set by the Train Controller before being used. 
     */
    public TCTrainInfoPane() {
        initComponents(); 
    }
    
    /**
     * Sets the train whose info to display to the user. 
     * 
     * @param train the train controlled by the Train Controller.
     */
    public void setSelectedTrain(Train train){
    
        this.selectedTrain = train;
    }
    
    /**
     * Sets the speed the train is currently going. 
     * 
     * @param speed the speed the train is going. 
     */
    public void setSpeedLabel(String speed){
       
        this.currentSpeed.setText(speed);
    }
    
    /**
     * Sets the power the train is currently producing. 
     * 
     * @param power the power the train is producing. 
     */
    public void setPowerLabel(String power){
    
        this.currentPower.setText(power);
    }
    
    /**
     * Sets the suggested speed for the train. This speed comes from the CTC. 
     * 
     * @param suggSpeed the suggested speed for the train. 
     */
    public void setSuggestSpeedLabel(String suggSpeed){
    
        this.suggestedSpeed.setText(suggSpeed);
    }
    
    /**
     * Retrieves the speed the train is going from the speed label. 
     * 
     * @return returns the text corresponding to the speed of the train from the speed label. 
     */
    public String getSpeedLabel(){
    
        return this.currentSpeed.getText(); 
    }
    
    /**
     * Retrieves the power the train is applying from the power label. 
     * 
     * @return returns the text corresponding to the power of the train from the power label. 
     */
    public String getPowerLabel(){
    
        return this.currentPower.getText(); 
    }
     
    /**
     * Retrieves the suggested speed of the train from the suggested speed label. 
     * 
     * @return returns the text corresponding to the suggested speed of the train from the suggested speed label. 
     */
    public String getSuggestedSpeedLabel(){
    
        return this.suggestedSpeed.getText(); 
    }
    
    /**
     * Updates the labels with the information based on the selected train.
     * 
     */
    public void refreshUI(){
    
        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.CEILING);
        
        this.setSpeedLabel(df.format( this.selectedTrain.getVelocity() ) );
        this.setPowerLabel(df.format( this.selectedTrain.getPower() ) );
        
        
        System.out.println(df.format( this.selectedTrain.getVelocity() ) );
        // FIX ME: This should be the suggested speed!
        //this.setSuggestSpeedLabel(df.format( this.selectedTrain.getSuggestedSpeed() ) );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speedLabel = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();
        currentSpeed = new javax.swing.JLabel();
        currentPower = new javax.swing.JLabel();
        suggSpeedLabel = new javax.swing.JLabel();
        authorityLabel = new javax.swing.JLabel();
        suggestedSpeed = new javax.swing.JLabel();
        maxAuthority = new javax.swing.JLabel();
        uiSeparatorOne = new javax.swing.JSeparator();
        speedUnit = new javax.swing.JLabel();
        powerUnit = new javax.swing.JLabel();
        suggSpeedUnit = new javax.swing.JLabel();
        authorityUnit = new javax.swing.JLabel();
        currentAuthority = new javax.swing.JLabel();
        authorityDivider = new javax.swing.JLabel();
        powerDivider = new javax.swing.JLabel();
        maxPower = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        speedLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        speedLabel.setText("Speed:");

        powerLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        powerLabel.setText("Power:");

        currentSpeed.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentSpeed.setText("0.00");

        currentPower.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentPower.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentPower.setText("0.00");

        suggSpeedLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        suggSpeedLabel.setText("Sugg. Speed:");

        authorityLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        authorityLabel.setText("Authority:");

        suggestedSpeed.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        suggestedSpeed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        suggestedSpeed.setText("0");

        maxAuthority.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        maxAuthority.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maxAuthority.setText("999");

        speedUnit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        speedUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        speedUnit.setText("MPH");

        powerUnit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        powerUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        powerUnit.setText("W");

        suggSpeedUnit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        suggSpeedUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        suggSpeedUnit.setText("MPH");

        authorityUnit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        authorityUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        authorityUnit.setText("mi");

        currentAuthority.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentAuthority.setText("999");

        authorityDivider.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        authorityDivider.setText("/");

        powerDivider.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        powerDivider.setText("/");

        maxPower.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        maxPower.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maxPower.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedUnit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(powerDivider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxPower)
                        .addGap(18, 18, 18)
                        .addComponent(powerUnit)))
                .addGap(31, 31, 31))
            .addComponent(uiSeparatorOne)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suggSpeedLabel)
                    .addComponent(authorityLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(currentAuthority)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorityDivider)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(suggestedSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxAuthority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suggSpeedUnit)
                    .addComponent(authorityUnit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(speedUnit)
                            .addComponent(currentSpeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(currentPower)
                                .addComponent(maxPower)
                                .addComponent(powerDivider))
                            .addComponent(powerUnit)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(speedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(powerLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uiSeparatorOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suggSpeedUnit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorityUnit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suggestedSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxAuthority)
                            .addComponent(currentAuthority)
                            .addComponent(authorityDivider)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(suggSpeedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorityLabel)))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorityDivider;
    private javax.swing.JLabel authorityLabel;
    private javax.swing.JLabel authorityUnit;
    private javax.swing.JLabel currentAuthority;
    private javax.swing.JLabel currentPower;
    private javax.swing.JLabel currentSpeed;
    private javax.swing.JLabel maxAuthority;
    private javax.swing.JLabel maxPower;
    private javax.swing.JLabel powerDivider;
    private javax.swing.JLabel powerLabel;
    private javax.swing.JLabel powerUnit;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JLabel speedUnit;
    private javax.swing.JLabel suggSpeedLabel;
    private javax.swing.JLabel suggSpeedUnit;
    private javax.swing.JLabel suggestedSpeed;
    private javax.swing.JSeparator uiSeparatorOne;
    // End of variables declaration//GEN-END:variables
}
