package TrainControllerComps;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
public class TCUtilityPanel extends javax.swing.JPanel {

    
    /**
     * Creates new form TCUtilityPanel
     */
    public TCUtilityPanel() {
        initComponents();
    }
     
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_AC = new javax.swing.ButtonGroup();
        btnGroup_Heat = new javax.swing.ButtonGroup();
        btnGroup_Lights = new javax.swing.ButtonGroup();
        btnGroup_LeftDoors = new javax.swing.ButtonGroup();
        btnGroup_RightDoors = new javax.swing.ButtonGroup();
        AC_Lbl = new javax.swing.JLabel();
        Heat_Lbl = new javax.swing.JLabel();
        Lights_Lbl = new javax.swing.JLabel();
        LeftDoor_Lbl = new javax.swing.JLabel();
        RightDoor_Lbl = new javax.swing.JLabel();
        Failure_Btn = new javax.swing.JRadioButton();
        Off_Btn = new javax.swing.JRadioButton();
        Failure_Btn1 = new javax.swing.JRadioButton();
        Off_Btn1 = new javax.swing.JRadioButton();
        On_Btn1 = new javax.swing.JRadioButton();
        Failure_Btn2 = new javax.swing.JRadioButton();
        Off_Btn2 = new javax.swing.JRadioButton();
        On_Btn2 = new javax.swing.JRadioButton();
        Failure_Btn3 = new javax.swing.JRadioButton();
        Off_Btn3 = new javax.swing.JRadioButton();
        On_Btn3 = new javax.swing.JRadioButton();
        Off_Btn4 = new javax.swing.JRadioButton();
        setHeat_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acTemp_TextField = new javax.swing.JTextField();
        Failure_Btn5 = new javax.swing.JRadioButton();
        setAC_Btn = new javax.swing.JButton();
        setHeat_Btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        AC_Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AC_Lbl.setText("A/C:");
        AC_Lbl.setToolTipText("Hey");

        Heat_Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Heat_Lbl.setText("Heat:");

        Lights_Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Lights_Lbl.setText("Lights:");

        LeftDoor_Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LeftDoor_Lbl.setText("Left Doors:");

        RightDoor_Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        RightDoor_Lbl.setText("Right Doors:");

        btnGroup_AC.add(Failure_Btn);
        Failure_Btn.setText("FAIL");

        btnGroup_AC.add(Off_Btn);
        Off_Btn.setText("OFF");
        Off_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffAirCond(evt);
            }
        });

        btnGroup_Lights.add(Failure_Btn1);
        Failure_Btn1.setText("FAIL");
        Failure_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Failure_Btn1ActionPerformed(evt);
            }
        });

        btnGroup_Lights.add(Off_Btn1);
        Off_Btn1.setText("OFF");
        Off_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffLights(evt);
            }
        });

        btnGroup_Lights.add(On_Btn1);
        On_Btn1.setText("ON");
        On_Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOnLights(evt);
            }
        });

        btnGroup_LeftDoors.add(Failure_Btn2);
        Failure_Btn2.setText("FAIL");

        btnGroup_LeftDoors.add(Off_Btn2);
        Off_Btn2.setText("CLOSE");
        Off_Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeLeftDoors(evt);
            }
        });

        btnGroup_LeftDoors.add(On_Btn2);
        On_Btn2.setText("OPEN");
        On_Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openLeftDoors(evt);
            }
        });

        btnGroup_RightDoors.add(Failure_Btn3);
        Failure_Btn3.setText("FAIL");
        Failure_Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Failure_Btn3ActionPerformed(evt);
            }
        });

        btnGroup_RightDoors.add(Off_Btn3);
        Off_Btn3.setText("CLOSE");
        Off_Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRightDoors(evt);
            }
        });

        btnGroup_RightDoors.add(On_Btn3);
        On_Btn3.setText("OPEN");
        On_Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRightDoors(evt);
            }
        });

        btnGroup_Heat.add(Off_Btn4);
        Off_Btn4.setText("OFF");
        Off_Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffHeat(evt);
            }
        });

        setHeat_TextField.setText("0");
        setHeat_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setHeat_TextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("°F");

        jLabel2.setText("°F");

        acTemp_TextField.setText("0");
        acTemp_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acTemp_TextFieldActionPerformed(evt);
            }
        });

        btnGroup_AC.add(Failure_Btn5);
        Failure_Btn5.setText("FAIL");
        Failure_Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Failure_Btn5ActionPerformed(evt);
            }
        });

        setAC_Btn.setText("Set");
        setAC_Btn.setToolTipText("Set the A/C to the specified temperature");
        setAC_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmitTemp_AC(evt);
            }
        });

        setHeat_Btn.setText("Set");
        setHeat_Btn.setToolTipText("Set the heat to the specified temperature");
        setHeat_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmitTemp_Heat(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lights_Lbl)
                            .addComponent(LeftDoor_Lbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acTemp_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setAC_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(Off_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Failure_Btn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(On_Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(Off_Btn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Failure_Btn2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Heat_Lbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(setHeat_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(setHeat_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(AC_Lbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(On_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Off_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Off_Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Failure_Btn1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Failure_Btn5, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RightDoor_Lbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(On_Btn3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Off_Btn3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Failure_Btn3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(AC_Lbl)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acTemp_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Off_Btn)
                    .addComponent(Failure_Btn)
                    .addComponent(setAC_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Heat_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(setHeat_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Failure_Btn5)
                    .addComponent(Off_Btn4)
                    .addComponent(setHeat_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(Lights_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(On_Btn1)
                    .addComponent(Off_Btn1)
                    .addComponent(Failure_Btn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(LeftDoor_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Failure_Btn2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(On_Btn2)
                        .addComponent(Off_Btn2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightDoor_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Off_Btn3)
                    .addComponent(Failure_Btn3)
                    .addComponent(On_Btn3))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void turnOffAirCond(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffAirCond
        System.out.println("Telling train to turn off air conditioning."); 
    }//GEN-LAST:event_turnOffAirCond

    private void turnOffLights(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffLights
        
        System.out.println("Telling train to turn off lights."); 
    }//GEN-LAST:event_turnOffLights

    private void turnOnLights(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOnLights
        // TODO add your handling code here:
        System.out.println("Telling train to turn on lights."); 
    }//GEN-LAST:event_turnOnLights

    private void closeLeftDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeLeftDoors
        
        System.out.println("Telling train to close left doors."); 
    }//GEN-LAST:event_closeLeftDoors

    private void openLeftDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openLeftDoors
       
        System.out.println("Telling train to open left doors."); 
    }//GEN-LAST:event_openLeftDoors

    private void closeRightDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRightDoors
        
        System.out.println("Telling train to close right doors."); 
    }//GEN-LAST:event_closeRightDoors

    private void openRightDoors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRightDoors
        
        System.out.println("Telling train to open right doors."); 
    }//GEN-LAST:event_openRightDoors

    private void turnOffHeat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffHeat
       
        System.out.println("Telling train to turn off heat.");  
    }//GEN-LAST:event_turnOffHeat

    private void Failure_Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Failure_Btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Failure_Btn3ActionPerformed

    private void setHeat_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setHeat_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setHeat_TextFieldActionPerformed

    private void acTemp_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acTemp_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acTemp_TextFieldActionPerformed

    private void Failure_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Failure_Btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Failure_Btn1ActionPerformed

    private void transmitTemp_Heat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmitTemp_Heat
      
        String temp = this.setHeat_TextField.getText();
        System.out.println("Telling the train to set temperature to " + temp + " for Heating unit"); 
    }//GEN-LAST:event_transmitTemp_Heat

    private void Failure_Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Failure_Btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Failure_Btn5ActionPerformed

    private void transmitTemp_AC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmitTemp_AC
        
        String temp = this.acTemp_TextField.getText();
        System.out.println("Telling the train to set temperature to " + temp + " for Air Conditioning unit"); 
        
    }//GEN-LAST:event_transmitTemp_AC


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AC_Lbl;
    private javax.swing.JRadioButton Failure_Btn;
    private javax.swing.JRadioButton Failure_Btn1;
    private javax.swing.JRadioButton Failure_Btn2;
    private javax.swing.JRadioButton Failure_Btn3;
    private javax.swing.JRadioButton Failure_Btn5;
    private javax.swing.JLabel Heat_Lbl;
    private javax.swing.JLabel LeftDoor_Lbl;
    private javax.swing.JLabel Lights_Lbl;
    private javax.swing.JRadioButton Off_Btn;
    private javax.swing.JRadioButton Off_Btn1;
    private javax.swing.JRadioButton Off_Btn2;
    private javax.swing.JRadioButton Off_Btn3;
    private javax.swing.JRadioButton Off_Btn4;
    private javax.swing.JRadioButton On_Btn1;
    private javax.swing.JRadioButton On_Btn2;
    private javax.swing.JRadioButton On_Btn3;
    private javax.swing.JLabel RightDoor_Lbl;
    private javax.swing.JTextField acTemp_TextField;
    private javax.swing.ButtonGroup btnGroup_AC;
    private javax.swing.ButtonGroup btnGroup_Heat;
    private javax.swing.ButtonGroup btnGroup_LeftDoors;
    private javax.swing.ButtonGroup btnGroup_Lights;
    private javax.swing.ButtonGroup btnGroup_RightDoors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton setAC_Btn;
    private javax.swing.JButton setHeat_Btn;
    private javax.swing.JTextField setHeat_TextField;
    // End of variables declaration//GEN-END:variables
}
