/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CommonUIElements.ClockAndLauncher;

import TrackModel.TrackModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andrew
 */
public class LoadFileWindow extends javax.swing.JFrame {

    TrackModel track;
    
    /**
     * Creates new form LoadFileWindow
     */
    public LoadFileWindow() {
        initComponents();  
    }
    
    /**
     * Creates new form LoadFileWindow
     */
    public LoadFileWindow(TrackModel track) {
        initComponents();
        this.track = track;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        redLineCSVTextField = new javax.swing.JTextField();
        greenLineCSVTextField = new javax.swing.JTextField();
        greenLineLinkageTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        redLineLinkageTextFile = new javax.swing.JTextField();
        loadFilesButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        browseGreenLineCSVButton = new javax.swing.JButton();
        browseRedLineLinkageButton = new javax.swing.JButton();
        browseGreenLineLinkageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Red Line:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Green Line:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Green Line Linkage:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Red Line Linkage:");

        loadFilesButton.setText("Load");
        loadFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFiles(evt);
            }
        });

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseRedLineFile(evt);
            }
        });

        browseGreenLineCSVButton.setText("Browse");
        browseGreenLineCSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGreenLineCSV(evt);
            }
        });

        browseRedLineLinkageButton.setText("Browse");
        browseRedLineLinkageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseGreenLineLinkage(evt);
            }
        });

        browseGreenLineLinkageButton.setText("Browse");
        browseGreenLineLinkageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseRedLineLinkage(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(greenLineCSVTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(redLineCSVTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseGreenLineCSVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(redLineLinkageTextFile, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(greenLineLinkageTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseRedLineLinkageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseGreenLineLinkageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadFilesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(redLineCSVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(greenLineCSVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseGreenLineCSVButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(redLineLinkageTextFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseRedLineLinkageButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(greenLineLinkageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseGreenLineLinkageButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(loadFilesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseRedLineFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseRedLineFile
       
        //open file browser
        JFileChooser PLCChoose = new JFileChooser();
        PLCChoose.setFileFilter(new FileNameExtensionFilter("CSV Files (.csv)", "csv"));
        int response = PLCChoose.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
          this.redLineCSVTextField.setText(PLCChoose.getSelectedFile().getAbsolutePath());
        } else {
        }  
    }//GEN-LAST:event_browseRedLineFile

    private void browseGreenLineCSV(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGreenLineCSV
        
        //open file browser
        JFileChooser PLCChoose = new JFileChooser();
        PLCChoose.setFileFilter(new FileNameExtensionFilter("CSV Files (.csv)", "csv"));
        int response = PLCChoose.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
          this.greenLineCSVTextField.setText(PLCChoose.getSelectedFile().getAbsolutePath());
        } else {
        }  
    }//GEN-LAST:event_browseGreenLineCSV

    private void browseRedLineLinkage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseRedLineLinkage
        
        
        //open file browser
        JFileChooser PLCChoose = new JFileChooser();
        PLCChoose.setFileFilter(new FileNameExtensionFilter("CSV Files (.csv)", "csv"));
        int response = PLCChoose.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
          this.redLineLinkageTextFile.setText(PLCChoose.getSelectedFile().getAbsolutePath());
        } else {
        }  
    }//GEN-LAST:event_browseRedLineLinkage

    private void browseGreenLineLinkage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseGreenLineLinkage
        //open file browser
        JFileChooser PLCChoose = new JFileChooser();
        PLCChoose.setFileFilter(new FileNameExtensionFilter("CSV Files (.csv)", "csv"));
        int response = PLCChoose.showOpenDialog(null);
        if (response == JFileChooser.APPROVE_OPTION){
          this.greenLineLinkageTextField.setText(PLCChoose.getSelectedFile().getAbsolutePath());
        } else {
        }  
    }//GEN-LAST:event_browseGreenLineLinkage

    private void loadFiles(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFiles
        
        String[] fNames = {this.redLineCSVTextField.getText(), this.greenLineCSVTextField.getText()} ;
        String[] fOverrideNames = {this.redLineLinkageTextFile.getText(), this.greenLineLinkageTextField.getText() }; 
        
        if (fNames.length == 2 && fOverrideNames.length == 2){
            
            this.track.readCSV(fNames, fOverrideNames);
        }        
    }//GEN-LAST:event_loadFiles

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadFileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadFileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadFileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadFileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadFileWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseGreenLineCSVButton;
    private javax.swing.JButton browseGreenLineLinkageButton;
    private javax.swing.JButton browseRedLineLinkageButton;
    private javax.swing.JTextField greenLineCSVTextField;
    private javax.swing.JTextField greenLineLinkageTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loadFilesButton;
    private javax.swing.JTextField redLineCSVTextField;
    private javax.swing.JTextField redLineLinkageTextFile;
    // End of variables declaration//GEN-END:variables
}
